server:
    port: 13900

spring:
    application:
        name: simpleLogin
    profiles:
        active: dev
    mvc:
        static-path-pattern: /!(index)/**
    banner:
        location: classpath:static/banner.txt
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: false
    mail:
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true