logging:
    level:
        root: info

server:
    port: 13900
    error:
        whitelabel:
            enabled: false

spring:
    application:
        name: simpleLogin
    profiles:
        active: dev
    mvc:
        static-path-pattern: /!(index)/**
    banner:
        location: classpath:static/banner.txt
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/simpleLogin?serverTimezone=GMT%2B8
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: false
    thymeleaf:
        enabled: false
    mail:
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            jedis:
                pool:
                    max-idle: 8
                    min-idle: 0
                    max-active: 8
                    max-wait: -1
    cache:
        type: redis
        redis:
            time-to-live: 600s
            cache-null-values: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        redirect-uri: http://localhost:13900/oauth/redirect
                        scope: user:email
                    google:
                        redirect-uri: http://localhost:13900/oauth/redirect
                        scope: profile%20email%20openid
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user
                        user-name-attribute: login
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo