spring:
    datasource:
        username: <your mysql username>
        password: <your mysql password>
    mail:
        host: smtp.gmail.com
        port: 587
        username: <your gmail address>
        password: <smtp password>
    data:
        redis:
            password: <your redis password>