server:
    port: 13900

spring:
    application:
        name: simpleLogin
    profiles:
        active: dev
    mvc:
        static-path-pattern: /!(index)/**
    banner:
        location: classpath:static/banner.txt
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: false
    mail:
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            jedis:
                pool:
                    max-idle: 8
                    min-idle: 0
                    max-active: 8
                    max-wait: -1